<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
		<GenerateDependencyFile>false</GenerateDependencyFile>
		<OutputPath>$(ProjectDir)..\Build\addons\counterstrikesharp\plugins\SharpTimer-StoreHud\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CounterStrikeSharp.API" Version="*" />
        <PackageReference Include="CS2MenuManager" Version="1.0.39" />
        <ProjectReference Include="..\SharpTimerAPI\SharpTimerAPI.csproj" />
    </ItemGroup>

	<Target Name="ExcludeStoreApiFiles" AfterTargets="Build">
		<Delete Files="$(OutputPath)SharpTimer-StoreHud.pdb" />
		<Delete Files="$(OutputPath)SharpTimerAPI.dll" />
	</Target>
</Project>
