<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
		<GenerateDependencyFile>false</GenerateDependencyFile>
		<OutputPath>$(ProjectDir)..\Build\addons\counterstrikesharp\plugins\SharpTimer-StoreHud\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CounterStrikeSharp.API" Version="*" />
        <PackageReference Include="CS2MenuManager" Version="1.0.39" />
        <ProjectReference Include="..\SharpTimerAPI\SharpTimerAPI.csproj" />
        <ProjectReference Include="..\StoreApi\StoreApi.csproj" />
    </ItemGroup>

    <!-- 确保StoreApi先编译 -->
    <ItemGroup>
        <ProjectReference Update="..\StoreApi\StoreApi.csproj">
            <Private>false</Private>
            <ReferenceOutputAssembly>true</ReferenceOutputAssembly>
            <CopyLocalSatelliteAssemblies>false</CopyLocalSatelliteAssemblies>
        </ProjectReference>
    </ItemGroup>

    <!-- 添加StoreApi的输出路径引用 -->
    <ItemGroup>
        <Reference Include="StoreApi">
            <HintPath>..\BuildOutput\shared\StoreApi\StoreApi.dll</HintPath>
        </Reference>
    </ItemGroup>

	<Target Name="ExcludeStoreApiFiles" AfterTargets="Build">
		<Delete Files="$(OutputPath)SharpTimer-StoreHud.pdb" />
		<Delete Files="$(OutputPath)SharpTimerAPI.dll" />
	</Target>
</Project>
