name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-24.04]
        target: [win-x64, linux-x64] # 构建 Windows 和 Linux 两个版本

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore SharpTimer.csproj

    - name: Build
      run: dotnet publish SharpTimer.csproj --configuration Release --runtime ${{ matrix.target }} --self-contained false --output build/${{ matrix.target }}

    - name: Package as ZIP
      run: |
        zip -r SharpTimer-${{ matrix.target }}.zip build/${{ matrix.target }}
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: SharpTimer-${{ matrix.target }}
        path: SharpTimer-${{ matrix.target }}.zip
