name: Build Package

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore SharpTimer.csproj

    - name: Build
      run: |
        dotnet publish SharpTimer.csproj \
          --configuration Release \
          --runtime linux-x64 \
          --self-contained false \
          --output build/addons/counterstrikesharp/plugins/SharpTimer

    - name: Copy additional files
      run: |
        mkdir -p build/cfg/SharpTimer
        mkdir -p build/addons/counterstrikesharp/plugins/SharpTimer
        mkdir -p build/addons/counterstrikesharp/plugins/SharpTimer/lang
        mkdir -p build/addons/counterstrikesharp/gamedata
        cp -r lang/* build/addons/counterstrikesharp/plugins/SharpTimer/lang/
        cp -r cfg/SharpTimer/stgamedata.json build/addons/counterstrikesharp/gamedata/
        cp -r cfg/SharpTimer/* build/cfg/SharpTimer/


        
    - name: Clean up old artifacts
      run: |
        rm -f SharpTimer-linux.zip
    - name: Package as ZIP
      run: |
        cd build
        zip -r ../SharpTimer-${{ github.ref_name }}.zip .
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SharpTimer-${{ github.ref_name }}
        path: SharpTimer-${{ github.ref_name }}.zip
